// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_Rf0-Xz2AHAksgxMKVfL0k8EymqOYsw',
    appId: '1:637539887913:web:7df5df773f8051a72b2538',
    messagingSenderId: '637539887913',
    projectId: 'viewouroptiontrade-5f91c',
    authDomain: 'viewouroptiontrade-5f91c.firebaseapp.com',
    storageBucket: 'viewouroptiontrade-5f91c.firebasestorage.app',
    measurementId: 'G-R75Q4QE96D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXW7266bHXBLny1-bDqTnbS7UFYuOPItg',
    appId: '1:637539887913:android:05b9c2d302020f5f2b2538',
    messagingSenderId: '637539887913',
    projectId: 'viewouroptiontrade-5f91c',
    storageBucket: 'viewouroptiontrade-5f91c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ80e2vXPktE9aYHw64C6y6q24Krrl-aI',
    appId: '1:637539887913:ios:26781e3a6f59b3cf2b2538',
    messagingSenderId: '637539887913',
    projectId: 'viewouroptiontrade-5f91c',
    storageBucket: 'viewouroptiontrade-5f91c.firebasestorage.app',
    iosBundleId: 'com.example.viewmytrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB_Rf0-Xz2AHAksgxMKVfL0k8EymqOYsw',
    appId: '1:637539887913:web:8289a0044d0e4cd52b2538',
    messagingSenderId: '637539887913',
    projectId: 'viewouroptiontrade-5f91c',
    authDomain: 'viewouroptiontrade-5f91c.firebaseapp.com',
    storageBucket: 'viewouroptiontrade-5f91c.firebasestorage.app',
    measurementId: 'G-2FDFVWXNPP',
  );
}
